/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import DAO.PerguntaDAO;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import modelo.Jogador;
import modelo.Pergunta;

/**
 *
 * @author Juscelino
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    private Jogador jogador;

    public Jogador getJogador() {
        return jogador;
    }

    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    List<Pergunta> perguntas; // perguntas do jogo
    List<Pergunta> todas;
    Pergunta patual; //pergunta atual
    ButtonGroup bg1;
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblpergunta = new javax.swing.JLabel();
        lblimagem = new javax.swing.JLabel();
        btna = new javax.swing.JRadioButton();
        btnb = new javax.swing.JRadioButton();
        btnc = new javax.swing.JRadioButton();
        btnd = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblerrar = new javax.swing.JLabel();
        lblparar = new javax.swing.JLabel();
        lblacertar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnpular = new javax.swing.JButton();
        btncartas = new javax.swing.JButton();
        btnparar = new javax.swing.JButton();
        btnconfirmar = new javax.swing.JButton();
        lbljogador = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblpergunta.setText("Pergunta:");

        lblimagem.setText("imagem");

        btna.setText("Opção 1");

        btnb.setText("Opção 2");

        btnc.setText("Opção 3");

        btnd.setText("Opção 4");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("0");

        jLabel4.setText("999");

        jLabel5.setText("9999");

        lblerrar.setText("Errar");

        lblparar.setText("Parar");

        lblacertar.setText("Acertar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblerrar)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblparar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lblacertar))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblerrar)
                    .addComponent(lblparar)
                    .addComponent(lblacertar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        btnpular.setText("Pular");

        btncartas.setText("Cartas");

        btnparar.setText("Parar");

        btnconfirmar.setText("Confirmar");
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnpular)
                .addGap(40, 40, 40)
                .addComponent(btncartas)
                .addGap(33, 33, 33)
                .addComponent(btnparar)
                .addGap(44, 44, 44)
                .addComponent(btnconfirmar)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpular)
                    .addComponent(btncartas)
                    .addComponent(btnparar)
                    .addComponent(btnconfirmar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lbljogador.setText("jogador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblimagem)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btna)
                            .addComponent(btnc)
                            .addComponent(btnb)
                            .addComponent(btnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(188, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbljogador)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpergunta)
                    .addComponent(lblimagem))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbljogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btna, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnd)
                        .addGap(56, 56, 56)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbljogador.setText(jogador.getLogin());
        //buscar as perguntas do nivel 1
        PerguntaDAO dao = new PerguntaDAO();
        perguntas = dao.listarNivel1();
         //colocar a primeira q aparece no patual
        patual = perguntas.get(0);
        //exibir na tela
        lblpergunta.setText(patual.getEnunciado());
        btna.setText(patual.getA());
        btnb.setText(patual.getB());
        btnc.setText(patual.getC());
        btnd.setText(patual.getD());
        
        bg1.add(btna);
        bg1.add(btnb);
        bg1.add(btnc);
        bg1.add(btnd);
    }//GEN-LAST:event_formWindowOpened

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
        //elimina a pergunta q esta sendo exibida
        Integer aux=5,aux1=0;
        PerguntaDAO dao = new PerguntaDAO();
        //todas = dao.listar();
        
        perguntas.remove(0);
        patual = perguntas.get(0);
        //exibir na tela
        lblpergunta.setText(patual.getEnunciado());
        btna.setText(patual.getA());
        btnb.setText(patual.getB());
        btnc.setText(patual.getC());
        btnd.setText(patual.getD());

        bg1.add(btna);
        bg1.add(btnb);
        bg1.add(btnc);
        bg1.add(btnd);
        //desmarcar tudo
        bg1.clearSelection();
        //depois q lista nivel1 vazia passar para proxima nivel / tela de fim quando lista de niveis acabar       
        if(aux == perguntas.size()){
            JOptionPane.showMessageDialog(rootPane, "Nível 2");
            perguntas = dao.listarNivel2();
            patual = perguntas.get(0);
            //exibir na tela
            lblpergunta.setText(patual.getEnunciado());
            btna.setText(patual.getA());
            btnb.setText(patual.getB());
            btnc.setText(patual.getC());
            btnd.setText(patual.getD());

            bg1.add(btna);
            bg1.add(btnb);
            bg1.add(btnc);
            bg1.add(btnd);
            //desmarcar tudo
            bg1.clearSelection();
            
        }
        
    }//GEN-LAST:event_btnconfirmarActionPerformed
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btna;
    private javax.swing.JRadioButton btnb;
    private javax.swing.JRadioButton btnc;
    private javax.swing.JButton btncartas;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JRadioButton btnd;
    private javax.swing.JButton btnparar;
    private javax.swing.JButton btnpular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblacertar;
    private javax.swing.JLabel lblerrar;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JLabel lbljogador;
    private javax.swing.JLabel lblparar;
    private javax.swing.JLabel lblpergunta;
    // End of variables declaration//GEN-END:variables
}
