/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * aumentar premio nivel 2 gravar no ranking o jogador quando qchegar na tela fim  e passar jogocompleto pra tela fim 
 */
package jogo;

import Audio.Audio;
import DAO.PerguntaDAO;
import java.util.List;
//import javax.swing.ButtonGroup;
//import javax.swing.JOptionPane;
import modelo.Jogador;
import modelo.JogoTodo;
import modelo.Pergunta;

/**
 *
 * @author Jiovana
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogoe
     */
    private Jogador jogador;
    private Integer nivel;
    private Integer ultimonivel;
    private PerguntaDAO dao;
    private Double premio;
    public Double premioaux;
    private JogoTodo todo;

    public JogoTodo getTodo() {
        return todo;
    }

    public void setTodo(JogoTodo todo) {
        this.todo = todo;
    }

    public Jogador getJogador() {
        return jogador;
    }

    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    List<Pergunta> perguntas; // perguntas do jogo
    List<Pergunta> todas;
    Pergunta patual; //pergunta atual
    //ButtonGroup bg1; -> buttonGroup1 já foi criado, o buttongroup é um função usada para gerenciar grupos de botões 
    //e não uma opção gráfica, mesmo  arrrastando ele n aparece mas está lá

    public Jogo() {
        initComponents();
        Audio audio = new Audio();

        //para tocar a música
        audio.tocar("worldondo");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        lblpergunta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbljogador = new javax.swing.JLabel();
        btna = new javax.swing.JRadioButton();
        btnb = new javax.swing.JRadioButton();
        btnc = new javax.swing.JRadioButton();
        btnd = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnpular = new javax.swing.JButton();
        btncartas = new javax.swing.JButton();
        btnparar = new javax.swing.JButton();
        btnconfirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblerro = new javax.swing.JLabel();
        lblpara = new javax.swing.JLabel();
        lblacerto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 15, true));

        lblpergunta.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblpergunta.setForeground(new java.awt.Color(255, 51, 0));
        lblpergunta.setText("PERGUNTA");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ivan_the_cute.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 3, true));

        lbljogador.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lbljogador.setForeground(new java.awt.Color(255, 51, 0));
        lbljogador.setText("jogador");

        btna.setBackground(new java.awt.Color(255, 255, 204));
        btna.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btna.setForeground(new java.awt.Color(255, 51, 0));
        btna.setText("Opção1");
        btna.setToolTipText("");

        btnb.setBackground(new java.awt.Color(255, 255, 204));
        btnb.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnb.setForeground(new java.awt.Color(255, 51, 0));
        btnb.setText("Opção2");
        btnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbActionPerformed(evt);
            }
        });

        btnc.setBackground(new java.awt.Color(255, 255, 204));
        btnc.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnc.setForeground(new java.awt.Color(255, 51, 0));
        btnc.setText("Opção3");

        btnd.setBackground(new java.awt.Color(255, 255, 204));
        btnd.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnd.setForeground(new java.awt.Color(255, 51, 0));
        btnd.setText("Opção4");

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));

        btnpular.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnpular.setForeground(new java.awt.Color(255, 51, 0));
        btnpular.setText("PULAR");
        btnpular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));

        btncartas.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btncartas.setForeground(new java.awt.Color(255, 51, 0));
        btncartas.setText("CARTAS");
        btncartas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));

        btnparar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnparar.setForeground(new java.awt.Color(255, 51, 0));
        btnparar.setText("PARAR");
        btnparar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));

        btnconfirmar.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btnconfirmar.setForeground(new java.awt.Color(255, 51, 0));
        btnconfirmar.setText("CONFIRMAR");
        btnconfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnpular, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncartas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnparar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpular)
                    .addComponent(btncartas)
                    .addComponent(btnparar)
                    .addComponent(btnconfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 5, true));

        lblerro.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblerro.setForeground(new java.awt.Color(255, 51, 0));
        lblerro.setText("0");

        lblpara.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblpara.setForeground(new java.awt.Color(255, 51, 0));
        lblpara.setText("0");

        lblacerto.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        lblacerto.setForeground(new java.awt.Color(255, 51, 0));
        lblacerto.setText("0");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("ERRAR");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("PARAR");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("ACERTAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblerro)
                        .addGap(42, 42, 42)
                        .addComponent(lblpara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblacerto)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblerro)
                    .addComponent(lblpara)
                    .addComponent(lblacerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iceland.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sweden.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/finland.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/denmark.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/norway.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnb)
                            .addComponent(btnc)
                            .addComponent(btnd)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpergunta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbljogador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btna)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblpergunta))
                            .addComponent(lbljogador))
                        .addGap(46, 46, 46)
                        .addComponent(btna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnd))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        todo = new JogoTodo();
        todo.setJogador(jogador);
        lbljogador.setText(jogador.getLogin());
        //buscar as perguntas do nivel 1
        dao = new PerguntaDAO();
        premio = 2500.00;
        premioaux = 0.0;

        nivel = 1;
        ultimonivel = 2;
        perguntas = dao.listarNivel1();
        //colocar a primeira q aparece no patual
        patual = perguntas.get(0);
        //exibir na tela
        lblpergunta.setText(patual.getEnunciado());
        btna.setText(patual.getA());
        btnb.setText(patual.getB());
        btnc.setText(patual.getC());
        btnd.setText(patual.getD());

        buttonGroup1.add(btna);
        buttonGroup1.add(btnb);
        buttonGroup1.add(btnc);
        buttonGroup1.add(btnd);

    }//GEN-LAST:event_formWindowOpened

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
        //verificar se acertou 
        todo = new JogoTodo();
        boolean acerto = false;

        patual.getCerta();

        //elimina a pergunta q esta sendo exibida
        dao = new PerguntaDAO();
        perguntas.remove(0);

        if (perguntas.isEmpty() && nivel.equals(ultimonivel)) {
            Fim f = new Fim();
            f.setVisible(true);
            this.setVisible(false);
        } else {
            if (btna.isSelected() == true && patual.getCerta().equalsIgnoreCase("a")) {
                premioaux = premioaux + premio;
                todo.setGanhos(premioaux);
                lblacerto.setText(todo.getGanhos().toString());
            } else if (btnb.isSelected() == true && patual.getCerta().equalsIgnoreCase("b")) {
                premioaux = premioaux + premio;
                todo.setGanhos(premioaux);
                lblacerto.setText(todo.getGanhos().toString());
            } else if (btnc.isSelected() == true && patual.getCerta().equalsIgnoreCase("c")) {
                premioaux = premioaux + premio;
                todo.setGanhos(premioaux);
                lblacerto.setText(todo.getGanhos().toString());
            } else if (btnd.isSelected() == true && patual.getCerta().equalsIgnoreCase("d")) {
                premioaux = premioaux + premio;
                todo.setGanhos(premioaux);
                lblacerto.setText(todo.getGanhos().toString());
            }
            //vai proximo nivel
            if (perguntas.isEmpty()) {
                perguntas = dao.listarNivel2();
                nivel++;
                if (btna.isSelected() == true && patual.getCerta().equalsIgnoreCase("a")) {
                    premioaux = premioaux + premio * 2;
                    todo.setGanhos(premioaux);
                    lblacerto.setText(todo.getGanhos().toString());
                } else if (btnb.isSelected() == true && patual.getCerta().equalsIgnoreCase("b")) {
                    premioaux = premioaux + premio * 2;
                    todo.setGanhos(premioaux);
                    lblacerto.setText(todo.getGanhos().toString());
                } else if (btnc.isSelected() == true && patual.getCerta().equalsIgnoreCase("c")) {
                    premioaux = premioaux + premio * 2;
                    todo.setGanhos(premioaux);
                    lblacerto.setText(todo.getGanhos().toString());
                } else if (btnd.isSelected() == true && patual.getCerta().equalsIgnoreCase("d")) {
                    premioaux = premioaux + premio * 2;
                    todo.setGanhos(premioaux);
                    lblacerto.setText(todo.getGanhos().toString());
                }
            }
            patual = perguntas.get(0);
            //exibir na tela
            lblpergunta.setText(patual.getEnunciado());
            btna.setText(patual.getA());
            btnb.setText(patual.getB());
            btnc.setText(patual.getC());
            btnd.setText(patual.getD());

            buttonGroup1.add(btna);
            buttonGroup1.add(btnb);
            buttonGroup1.add(btnc);
            buttonGroup1.add(btnd);
            buttonGroup1.clearSelection();//desmarcar tudo
      
        }
    }//GEN-LAST:event_btnconfirmarActionPerformed

    private void btnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btna;
    private javax.swing.JRadioButton btnb;
    private javax.swing.JRadioButton btnc;
    private javax.swing.JButton btncartas;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JRadioButton btnd;
    private javax.swing.JButton btnparar;
    private javax.swing.JButton btnpular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblacerto;
    private javax.swing.JLabel lblerro;
    private javax.swing.JLabel lbljogador;
    private javax.swing.JLabel lblpara;
    private javax.swing.JLabel lblpergunta;
    // End of variables declaration//GEN-END:variables
}
